var DATA = {
  "Centre Essonne": {
    "BONDOUFLE": [
      "BON-SLT-001 - Rue de Villeroy - All. Edmond Delfours - Rue des Trois Parts",
      "BON-SLT-002 - Rue de Villeroy - Rue des Clos - Rue des Trois Parts",
      "BON-SLT-003 - Rue de Villeroy - Rue Gutemberg",
      "BON-SLT-004 - Rue Gutemberg - Rue Georges Pompidou"
    ],
    "EVRY": [
      "EVC-SLT-001 - N7 Bd. Jean Jaures -Centre Hospitalier SUD Francilien",
      "EVC-SLT-002 - RN7 (Bd Jean Jaures) - Rue de l'Internationale - Rue Pierre Fontaine - SNECMA",
      "EVC-SLT-003 - Bd du Marechal De Lattre de Tassigny - Rue du Bel Air - Ch. De la Grange Feu Louis",
      "EVC-SLT-004 - Bd. Du Marechal De Lattre de Tassigny - Bd des Coquibus - Rue Maurice Ravel",
      "EVC-SLT-005 - Bd. Du Marechal De Lattre de Tassigny - Rond Point du Parc aux Lievres",
      "EVC-SLT-006 - Bd. Des Coquibus -Gare RER Bras de Fer",
      "EVC-SLT-007 - Bd des Coquibus - RN7 (Entrees/Sorties)",
      "EVC-SLT-008 - Bd des Coquibus - Imp. Alexis Trinquet",
      "EVC-SLT-009 - Bd des Coquibus - Bd Louise Michel",
      "EVC-SLT-010 - Bd des Coquibus - Rue Charles Fourier",
      "EVC-SLT-011 - Bd des Coquibus - Bd de France - Rue des Gaston Cremieux",
      "EVC-SLT-012 - Bd des Coquibus - Rue Henri Rochefort",
      "EVC-SLT-013 - Bd des Coquibus - Rue des Mazieres",
      "EVC-SLT-014 - Bd des Coquibus - Cours Blaise Pascal - Cours Mgr Romero",
      "EVC-SLT-015 - P.P. Bd Francois Mitterand - Gare",
      "EVC-SLT-016 - Bd Francois Mitterrand - Rue Ambroise Croizat - Rue Pere Andre Jarlan",
      "EVC-SLT-019 - Bd. Louise Michel - Place des Federes",
      "EVC-SLT-020 - Bd Louise Michel - Rue de l'Internationale - Rue Jean Malezieux",
      "EVC-SLT-021 - Bd de l'Yerres - Rue de l'Essonne",
      "EVC-SLT-022 - Bd de L'Yerres - Rue Boissy d'Anglas - Voie TU",
      "EVC-SLT-023 - Bd de l'Yerres - Acces Les Estudines - Voie TU",
      "EVC-SLT-024 - Bd de l'Yerres - Av. du Lac",
      "EVC-SLT-025 - Bd des Champs Elysees - Rue de l'Abbe Gregoire - Parking Indigo",
      "EVC-SLT-029 - Bd des Champs Elysees - Bd de l'Europe",
      "EVC-SLT-030 - Bd des Champs Elysees - Rue des Galants Courts",
      "EVC-SLT-031 - Bd des Champs Elysees - Bd de L'Ecoute S'Il Pleut",
      "EVC-SLT-032 - Bd des Champs Elysees - Rue Jules Valles",
      "EVC-SLT-033 - Bd des Champs Elysees - Clinique de l'Essone - Voie TU",
      "EVC-SLT-034 - Bd des Champs Elysees - Rue Paul Claudel - Rue du Bois Guillaume",
      "EVC-SLT-035 - Bd des Champs Elysees - RN7 (Entrees/Sorties)",
      "EVC-SLT-036 - Bd des Champs Elysees - Rue Gutenberg",
      "EVC-SLT-037 - Av. de la Liberte - Rue des Grands Champs",
      "EVC-SLT-038 - Av. de la Liberte - Av. de Ratisbonne",
      "EVC-SLT-039 - Bd. Decauville - All. L.B. de Bourbon",
      "EVC-SLT-040 - Bd Decauville - Rue Montespan - Rue d'Antin",
      "EVC-SLT-041 - Bd. Decauville - Av. Nowy Targ",
      "EVC-SLT-042 - Bd. Decauville - Bd Aguado - Rue Emmanuel Pastre",
      "EVC-SLT-043 - P.P. Rue Rossini",
      "EVC-SLT-044 - Bd du Marechal Leclerc - Av. Nowy Targ - Voie TU",
      "EVC-SLT-045 - Bd de l'Europe - Rue des Mazieres - Rue du Facteur Cheval",
      "EVC-SLT-046 - Bd de l'Europe - Desserte Aristide Canlorbe - Mc Donald",
      "EVC-SLT-047 - Bd de l'Europe - Av. de l'Orme a Martin",
      "EVC-SLT-048 - Bd de l'Europe - Bd de L'Ecoute S'Il Pleut",
      "EVC-SLT-049 - Rue Montespan - Rue Descartes",
      "EVC-SLT-050 - Rue des Galants Courts - Rue du Facteur Cheval - Voie TU",
      "EVC-SLT-051 - P.P. 205 Rue Pierre et Marie Curie",
      "EVC-SLT-052 - Rue Jules Valles - Pl. Salvador Allende - Voie TU",
      "EVC-SLT-053 - Bd de L'Ecoute S'Il Pleut - Rue Jean Anouilh",
      "EVC-SLT-054 - Rue du Bois Sauvage - Av. de l'Aunette - Voie TU",
      "EVC-SLT-055 - Rue du Bois Guillaume - Rte de Mennecy",
      "EVC-SLT-062 - Rue Promethee - Av. Nowy Targ (Voie TU)",
      "EVC-SLT-063 - Bd de France - Rue Promethee",
      "EVC-SLT-064 - Bd de France - Av. de la Prefecture",
      "EVC-SLT-065 - D91 - D93 - Bd de France-Georges Pompidou - Bretelle N7 Entree/Sortie",
      "EVC-SLT-066 - P.P. Av. du Marechal Juin",
      "EVC-SLT-067 - Av. du General Patton - Av. de Mousseau - Rue du 8 Mai 1945",
      "EVC-SLT-068 - Av. du General Patton - Av. Fragonard",
      "EVC-SLT-069 - Av. de Mousseau - Av. Fragonard - Rue Claude Debussy",
      "EVC-SLT-070 - Imp. Alexis Trinquet - Voie TU",
      "EVC-SLT-071 - Imp. Jean Malezieux - All. De la Butte Rouge (VoieTU)",
      "EVC-SLT-072 - Rue Henri Rochefort - All. De la Butte Rouge (Voie TU)",
      "EVC-SLT-073 - Rue de l'Essonne - Rue de l'Ecole - Voie TU",
      "EVC-SLT-074 - All. Boissy d'Anglas - Voie TU - Bd. De l'Yerres",
      "EVC-SLT-075 - Av. Simone Veil - Voie TU + P.P. TU",
      "EVC-SLT-076 - Cours Monseigneur Romero - Voie TU"
    ],
    "COURCOURONNES": [
      "EVC-SLT-017 - Av. Paul Delouvrier -Bd des Champs Elysees - Bd Francois Mitterand",
      "EVC-SLT-018 - Av. Paul Delouvrier - Sortie A6",
      "EVC-SLT-026 - Bd des Champs Elysees - Rue Georges Brassens - Rue Leopold Sedar Senghor",
      "EVC-SLT-027 - Bd des Champs Elysees - Rue Jaques Tati",
      "EVC-SLT-028 - Bd des Champs Elysees - Rue Jean Renoir",
      "EVC-SLT-056 - Rue Jean Renoir - Voie TU",
      "EVC-SLT-057 - Rue du Marquis de Raies - Rue des Freres Lumiere - Rue Jacques Tati",
      "EVC-SLT-058 - Rue du Marquis de Raies - Rue Georges Brassens",
      "EVC-SLT-059 - Rue du Marquis de Raies - Place du Printemps",
      "EVC-SLT-060 - Av. de l'Orme a Martin - Rue du Marquis de Raies - Rue du Plessis Briard",
      "EVC-SLT-061 - Rue du Pont Amar - Rue de la Boissee - Voie TU",
      "EVC-SLT-077 - Av. de l'Orme a Martin - Rue du Pont Amar",
      "EVC-SLT-078 - Av. de l'Orme a Martin - Rue des Osiers - Rue Jean Mermoz",
      "EVC-SLT-079 - Av. Pierre Beregovoy - Av. G.Clemenceau",
      "EVC-SLT-080 - Av. Pierre Beregovoy - Rue de la Cerisaie",
      "EVC-SLT-081 - Av. Pierre Beregovoy - Rue du Cygnes",
      "EVC-SLT-082 - Av. Pierre Beregovoy - Rue Ambroise Pare - Parc du Lac",
      "EVC-SLT-083 - Rue Alcide de Gasperi - Av. de la Petite Montagne - Rue de la Mare Neuve - Voie TU",
      "EVC-SLT-084 - Rue Noel Marteau - Rue Joseph Letien",
      "390 (eiffage) - COURCOURONNES TRAM T12",
      "391 (eiffage) - COURCOURONNES TRAM T12"
    ],
    "GRIGNY": [
      "GRI-SLT-001 - P.P. Av. Emile Aillaud - Rue du Ravin",
      "GRI-SLT-002 - Av. Emile Aillaud - Rue Dedale - Rue du Ravin",
      "GRI-SLT-003 - Av. Emile Aillaud - Rue Condorcet - Voie Athena",
      "GRI-SLT-004 - Av. Emile Aillaud - Rue Diderot - Rue des Batisseurs",
      "GRI-SLT-005 - P.P. Av. de la premiere armee Rhin Danube - Rue Avicenne - Mosquee de Grigny",
      "GRI-SLT-006 - Av. de la premiere armee Rhin Danube - Ch. de Corbeil",
      "GRI-SLT-007 - Av. de la premiere armee Rhin Danube - Gare Grigny Centre RER",
      "GRI-SLT-008 - Rue de Louise Michel Rte de Corbeil Sortie parking Square Rodin",
      "GRI-SLT-009 - Rte de Corbeil Rue des Jardins de la Ferme - Rle du Cure",
      "GRI-SLT-010 - Rte de Corbeil - Rue Pierre Brossolette - Ch. du Plessis",
      "GRI-SLT-011 - Route de Corbeil Ecole Maternelle les Tilleuls - Mairie de Grigny",
      "GRI-SLT-012 - Ch. du Moulin Rue Guy Mocquet - Rue de Schio",
      "GRI-SLT-013 - Ch. du Plessis Promenade du Canal - Rue du 17 Octobre 1961",
      "GRI-SLT-014 - RN7 Rue Ferdinand De Lesseps",
      "GRI-SLT-015 - RN7 - Sortie Truffaut",
      "GRI-SLT-016 - RN7 - Ch. du Port - Rue du Port",
      "GRI-SLT-017 - P.P. 8/10 Rue Gustave Eiffel (Sortie entreprises FAYAT et SAML)"
    ],
    "LISSES": [
      "LIS-SLT-551 - LISSES 8 Mai 1945 - Peupliers",
      "LIS-SLT-552 - LISSES 8 Mai 1945 - Adam de la Halle",
      "LIS-SLT-553 - LISSES 8 Mai 1945 - Christine de Pisan",
      "LIS-SLT-554 - LISSES 8 Mai 1945 - Parcs",
      "LIS-SLT-555 - LISSES Parcs - Malines",
      "LIS-SLT-556 - LISSES Paris - Bois de la Place",
      "LIS-SLT-557 - LISSES Paris - Corbeil",
      "LIS-SLT-558 - LISSES Gal de Gaulle - Aulnes",
      "LIS-SLT-559 - LISSES Parcs - M.Roche",
      "LIS-SLT-560 - LISSES D26 - Clos au pois",
      "LIS-SLT-561 - LISSES Parcs - Leonard de Vinci",
      "LIS-SLT-575 - LISSES Villabe - entree A6",
      "LIS-SLT-576 - LISSES Corbeil - Longaines"
    ],
    "RIS-ORANGIS": [
      "200 (eiffage) - RIS-ORANGIS RN7 - Glaise",
      "RIS-SLT-201 - RIS-ORANGIS RN7 - Reckitt",
      "202 - RIS-ORANGIS RN7 - Clos",
      "203 - RIS-ORANGIS RN7 - E.Bonte",
      "204 - RIS-ORANGIS RN7 - J.jaures",
      "205 - RIS-ORANGIS RN7 - Fontaine",
      "206 - RIS-ORANGIS P.Brossolette - Fusilles",
      "207 - RIS-ORANGIS P.Brossolette - Grigny",
      "207bis - RIS-ORANGIS P.Brossolette - Sand",
      "208 - RIS-ORANGIS P.Brossolette - Papin",
      "209 - RIS-ORANGIS P.Brossolette - Cime",
      "210 - RIS-ORANGIS P.Brossolette - Mouchot",
      "211 - RIS-ORANGIS P.Brossolette - Monthlery",
      "212 - RIS-ORANGIS Aunette - College J.Lurcat",
      "213 - RIS-ORANGIS Resistance - Plessis Briard",
      "214 - RIS-ORANGIS P.P Cime",
      "215 - RIS-ORANGIS P.P Maternelle Fauvettes",
      "216 - RIS-ORANGIS Grigny - J.Jaures",
      "217 - RIS-ORANGIS Grigny - Chateau d'Eau",
      "218 - RIS-ORANGIS Grigny - Clos Langlet",
      "219 - RIS-ORANGIS PP - RN7",
      "220 - RIS-ORANGIS Chateau D'Eau - Moulin a Vent",
      "221 - RIS-ORANGIS Chateau D'Eau - Orangis Picasso",
      "222 - RIS-ORANGIS Resistance - LE PLAN2",
      "223 - RIS-ORANGIS RN7 - P.P Total Acces"
    ],
    "VILLABE": [
      "VIL-SLT-601 - VILLABE Sortie BUS - Route de Lisses",
      "VIL-SLT-602 - VILLABE Vielle cote - Bas cornus",
      "VIL-SLT-603 - VILLABE Vielle cote - 8Mai 1945",
      "VIL-SLT-604 - VILLABE Sortie Ecole J.Jaures",
      "VIL-SLT-605 - VILLABE Ormoy - Bas des Brettes"
    ]
  },
  "Seine Essonne": {
    "COMBS-LA-VILLE": [
      "CLV-SLT-001 - Av de Quincy - Av Victor Hugo - All. des Peupliers",
      "CLV-SLT-002 - P.P. Av de Quincy - Ecole Beausoleil",
      "CLV-SLT-003 - Av. du Gal. Leclerc - Av de la Republique - Rue Sommeville - Rue Therese Delapierre",
      "CLV-SLT-004 - Rue Jean Moulin - Rue de Lieusaint",
      "CLV-SLT-005 - Rue Pablo Picasso - Rue Jean Moulin - Rue Jean Francois Millet",
      "CLV-SLT-006 - P.P. Rue de l'Abreuvoir - All. des Grives",
      "CLV-SLT-007 - Rue du Chene - Rue du Marche - Av. de la Marrache",
      "CLV-SLT-008 - P.P. Lycee Jacques Prevert - Av. Jean Jaures",
      "CLV-SLT-009 - P.P. Ecole Oree du Bois - Rue du Bois l'Eveque"
    ],
    "CORBEIL-ESSONNES": [
      "COR-SLT-001 - RN7 (Bd John Kennedy) - RD191 (Av. des Roissy Hauts)",
      "COR-SLT-002 - RN7 (Bd. John Kennedy) - Ch. des Ronfleurs",
      "COR-SLT-003 - RN7 (Bd John Kennedy) - Ch. De la Cavignon",
      "COR-SLT-004 - P.P. 161 Bd. John Kennedy RN7",
      "COR-SLT-005 - RN7 (Bd John Kennedy) - Rue Balzac - Rue du Chene",
      "COR-SLT-006 - RN7 (Bd John Kennedy) - Ecole Pauline Kergomard",
      "COR-SLT-007 - RN7 (Bd John Kennedy) - Ch. du Cgb (Chemin de Fer de Grande Banlieue)",
      "COR-SLT-008 - RN7 (Bd John Kennedy) - Rue St Lazare",
      "COR-SLT-009 - RN7 (Bd John Kennedy - Bd de Fontainebleau) - Bd Henri Dunant",
      "COR-SLT-010 - RN7 (Rue de Paris - Bd de Fontainebleau) - Rue de la Dauphine - Rue Louis Joyeux",
      "COR-SLT-011 - RN7 (Rue de Paris) - Rue de Gournay - Rue d'Angouleme",
      "COR-SLT-012 - RN7 (Rue de Paris) - Pl. Leon Casse - Rue du Pere Legris",
      "COR-SLT-013 - RN7 (Rue de Paris) - Rue Marchand",
      "COR-SLT-014 - QUICK: Pl. de Sindelfingen - Rue de Paris - Rue Feray - Rue de Robinson - Bd Georges Michel - Bd du Mal. De Lattre de Tassigny",
      "COR-SLT-015 - QUICK: Pl. de Sindelfingen - Rue de Paris - Rue de Robinson - Bd du Mal. De Lattre de Tassigny - (Armoire a cote de COR-SLT-03)",
      "COR-SLT-016 - RN7 (Bd Jean Jaures) -Rue de l'Alouette",
      "COR-SLT-017 - RN7 (Bd Jean Jaures) - Route des Lisses",
      "COR-SLT-018 - P.P. RN7 (Bd Jean Jaures) - Av Serge Dassault - Sortie Parking Lycee Robert Doisneau",
      "COR-SLT-019 - RN7 (Bd Jean Jaures) - Pl. des Anciens Combattants d'Afn et d'Indochine",
      "COR-SLT-020 - RN7 (Bd. Jean Jaures) Entree/Sortie RN104",
      "COR-SLT-021 - Av. du 8 Mai 1945 - Rue des Vergers - Rue la Fontaine",
      "COR-SLT-022 - Av. Gal. De Gaulle - Av. Serge Dassault - Voie TZEN4",
      "COR-SLT-023 - Av. Serge Dassault - Rue Henri Matisse - Voie TZEN4",
      "COR-SLT-024 - Av. Serge Dassault - Rue de la Bruyere - Voie TZEN4",
      "COR-SLT-025 - Av. Serge Dassault - Rue Charles Robin - Voie TZEN4",
      "COR-SLT-026 - Rue Emile Zola - Av. Serge Dassault - Voie TZEN4 - Gare routiere",
      "COR-SLT-027 - Rue Emile Zola - Rue La Fayette",
      "COR-SLT-028 - Rue Emile Zola - Av. Leon Blum",
      "COR-SLT-029 - Av. Paul Maintenant - Rte de Lisses",
      "COR-SLT-030 - Av. Paul Maintenant - Rue Jacques Anquetil - Rue des Pepinieres",
      "COR-SLT-031 - Av. Paul Maintenant - McDonald's",
      "COR-SLT-032 - Av. du Gal. De Gaulle - Rue Pablo Picasso",
      "COR-SLT-033 - P.P. Av. du Gal. De Gaulle - College Leopold Sedar Senghor",
      "COR-SLT-034 - P.P. Mosquee: Av. du Gal. De Gaulle - Rue Auguste Renoir",
      "COR-SLT-035 - Rue du Mal. De Lattre de Tassigny - Parking \"Marche Frais\"",
      "COR-SLT-036 - Av. Carnot - Rue Feray",
      "COR-SLT-037 - Av. Carnot - Rue du Dr Vignes",
      "COR-SLT-038 - Rue du Gal. Leclerc - Rue Felicien Rops",
      "COR-SLT-039 - Rue du Gal. Leclerc - Rue de Seine",
      "COR-SLT-040 - Rue de Seine - Av. Darblay - Rue du Gal. Lucotte",
      "COR-SLT-041 - Bd. Louis Lecouillard - Rue Fernand Laguide - Rue de la Nacelle",
      "COR-SLT-042 - Rue de la nacelle - Rue Bernardin de Saint-Pierre",
      "COR-SLT-043 - P.P. Rue de la Papeterie - Rue Paul et Virginie",
      "COR-SLT-044 - Bd Combes Marne - Rue d'Angouleme",
      "COR-SLT-045 - Place d'Essonnes - Bd Combes Marnes - Bd Jules Valles",
      "COR-SLT-046 - Bd Henri Dunant - Av. du Pr. Allende- Caserne Sapeurs Pompiers",
      "COR-SLT-047 - Bd. Henri Dunant - Rue Marcel Paul",
      "COR-SLT-048 - Boulevard Henri Dunant - Rue Gilles de Corbeil",
      "COR-SLT-049 - Bd. Henri Dunant - CDAU SDIS91 (Centre de secours) - Ch. Des Mozards",
      "COR-SLT-050 - Bd Henri Dunant - Av. Rene Pierre - Rue Belvedere",
      "COR-SLT-051 - Bd Henri Dunant - Rue de la Dauphine",
      "COR-SLT-052 - Bd Henri Dunant Rue Lamartine",
      "COR-SLT-053 - Bd Henri Dunant - Rue de Gournay",
      "COR-SLT-054 - Rue Chevalier - Av. Carnot Bd Henri Dunant Rue Saint Spire",
      "COR-SLT-055 - P.P. St Spire - Rue des Fosses",
      "COR-SLT-056 - Quai Jacques Bourgoin - Rue de la Triperie - Gare Routiere",
      "COR-SLT-057 - Pl. du Comte Haymon - Quai Mauzaisse - Quai Jacques Bourgoin - Rue St Spire - Rue Notre Dame",
      "COR-SLT-058 - Quai de l'Apport Paris - Rue Decauville",
      "COR-SLT-059 - Quai de l'Apport Paris - Rue Fernand Raynaud (Sortie TATA)",
      "COR-SLT-060 - Quai Maurice Riquiez - Quai des Platanes - Rue de Montgarde",
      "COR-SLT-061 - Quai Maurice Riquiez - Rue de la Tuilerie - Rue de la Guinguette",
      "COR-SLT-062 - Rue Waldeck Rousseau - Rue Audiffred Bastide - Rue du 14 Juillet",
      "COR-SLT-063 - Rue Waldeck Rousseau - Square des Peupliers",
      "COR-SLT-063 - P.P. Ecole Theodore Steeg - Rue Paul Bert"
    ],
    "ETIOLLES": [
      "ETI-SLT-001 - RD448 (2 Av. du General De Gaulle) - Residence les deux marquises",
      "ETI-SLT-002 - RD448 (Av. de la Font au Soulier) - Av. Charles De Gaulle - Ch. Du Port aux Paveurs",
      "ETI-SLT-003 - RD448 (Av. de la Font au Soulier) - RD331 (Rue Collardeau)",
      "ETI-SLT-004 - RD331 (Rue des Bordes) - Rue des Patenottes - Ch. De Villouvette"
    ],
    "LE COUDRAY-MONTCEAUX": [
      "LCM-SLT-001 - RN7 (Av. Charles de Gaulle) - Rue de Bouligneau - All. du Coudray",
      "LCM-SLT-002 - Av. Charles de Gaulle - Rue du Martelet - All. du Coudray - Gare routiere",
      "LCM-SLT-003 - Av. Charles de Gaulle - All. des Ecureuils - Rue de la Clef des Champs",
      "LCM-SLT-004 - Av. Charles de Gaulle - Rue Gabrielle d'Estrees - Rue des Verts Domaines",
      "LCM-SLT-005 - RN7 (Av. Charles de Gaulle) - Rue de Milly - P.P. Rond Point du Grand Pacha de l'Himalaya",
      "LCM-SLT-006 - RN7 (Bd. John Kennedy) - Sortie X-FAB France",
      "LCM-SLT-007 - RD191 (Av. des Roissy Hauts) - Entree X-FAB France"
    ],
    "SAINT-GERMAIN-LES-CORBEIL": [
      "SGC-SLT-01 - N 01 De Gaulle Val Fleury",
      "SGC-SLT-02 - N 02 Rte de Lieusaint mairie Darblay",
      "SGC-SLT-03 - N 03 Rochefort tuilerie",
      "SGC-SLT-04 - N 04 Leclerc Etiolles Villouvette"
    ],
    "MORSANG SUR SEINE": [
      "MORSANG SUR SEINE"
    ]
  },
  "Senart": {
    "LIEUSAINT": [
      "LIE-SLT-01 - D402 OLYMPE DE GOUGE",
      "LIE-SLT-02 - AV.PIERRE POINT SORTIE GARE ROUTIERE",
      "LIE-SLT-03 - Rue du COLOMBIER RUE DE PARIS",
      "LIE-SLT-04 - Ave PIERRE POINT Bd OLYMPE DE GOUGE",
      "LIE-SLT-05 - D402 COTE DE L ENTRE DEUX",
      "LIE-SLT-06 - D402 FERME DE VARATRE",
      "LIE-SLT-07 - AV PIERRE POINT - PARIS",
      "LIE-SLT-08 - D402 MOULIN A VENT",
      "LIE-SLT-09 - TRAIT D UNION COTE DE LA COMMUNAUTE",
      "LIE-SLT-10 - TRAIT D UNION HOTEL CLARION SUITES",
      "LIE-SLT-11 - TRAIT D UNION POINT DE VUE NORD",
      "LIE-SLT-12 - TRAIT D UNION ALLEE DE LAVANT SCENE",
      "LIE-SLT-13 - TRAIT D UNION POINT DE VUE SUD",
      "LIE-SLT-14 - POINT DE VUE ALLEE DE L ECHANGE",
      "LIE-SLT-15 - POINT DE VUE CARRE DES ARTS",
      "LIE-SLT-16 - POINT DE VUE ALLEE DE LA TOLERANCE",
      "LIE-SLT-17 - ALLEE DE LA TOLERANCE COTE DE L ENTRE DEUX",
      "LIE-SLT-18 - PP BD EUROPE",
      "LIE-SLT-19 - TRAIT UNION -COTE DE LA BIENVENUE"
    ],
    "MOISSY-CRAMAYEL": [
      "MOI-SLT-01 - ALTERNAT 1 RUE DENIS PAPIN ZAC DARVIGNY"
    ],
    "SAINT-PIERRE-DU-PERRAY": [
      "SPP-SLT-01 - Rue de la MAIRIE Ecole CHANTEFABLES",
      "SPP-SLT-02 - Rue Victor HUGO Allee de VILLERAY",
      "SPP-SLT-03 - GENDARMERIE CHEMIN DE BRIE",
      "SPP-SLT-04 - RTE DE MONTGARDE ALLEE BOURGOIN",
      "SPP-SLT-19 - Bd CHRISTIAN JULLIEN RUE DES CYGNES",
      "SPP-SLT-20 - Bd CHRISTIAN JULLIEN RUE MOZART",
      "SPP-SLT-21 - AV. TOUR MAURY RUE DU GRAND MAURY",
      "SPP-SLT-23 - AV. TOUR MAURY RUE DES PRES HAUTS",
      "SPP-SLT-25 - AV. TOUR MAURY RUE DE LA MARE A TISSIER",
      "SPP-SLT-26 - AV.TOUR MAURY RTE DE VILLEPECLE",
      "SPP-SLT-27 - D33 PASSAGE DE MAUPERTHUIS"
    ],
    "SAVIGNY-LE-TEMPLE": [
      "SVY-SLT-01 - RD50 - CUEILLETTE",
      "SVY-SLT-02 - AVENUE 8 MAI 1945 - RUE DE LA GRANGE",
      "SVY-SLT-03 - AVENUE DE GAULLE - RUE DES PROVINCES",
      "SVY-SLT-04 - AVENUE DE GAULLE - AVENUE DE L EUROPE",
      "SVY-SLT-05 - AVENUE DE GAULLE - RUE DE ROUGEAU",
      "SVY-SLT-06 - RUE DE ROUGEAU - ALLEE DE PERSPECTIVE"
    ],
    "SOISY-SUR-SEINE": [
      "SOI-SLT-01 - SOISY-SUR-SEINE RD448 / Liberation / Du Rendez-Vous / Rue des Meillottes",
      "SOI-SLT-02 - SOISY-SUR-SEINE Bd de la republique / Bd Briand / Bd Vandeul",
      "SOI-SLT-03 - SOISY-SUR-SEINE E.Warin / F.Bourgeois / Vandeul / L'Oiseau",
      "SOI-SLT-04 - SOISY-SUR-SEINE De Gaulle / Marronnier / Residence des 2 Marquises",
      "SOI-SLT-05 - SOISY-SUR-SEINE De Gaulle / Seine / Berthelot"
    ],
    "TIGERY": [
      "TGY-SLT-01 - Rte de Lieusaint Rue Roland Delplanque",
      "TGY-SLT-02 - P.P. BOULEVARD DES PAYS-BAS",
      "TGY-SLT-03 - Rte de Lieusaint - Rue de la Bergerie - Rue du Cmdt. Maurice Lissac"
    ],
    "NANDY": [
      "NANDY"
    ],
    "REAU": [
      "REAU"
    ],
    "SAINTRY-SUR-SEINE": [
      "SAINTRY-SUR-SEINE"
    ],
    "VERT-SAINT-DENIS": [
      "VERT-SAINT-DENIS"
    ]
  }
};
