var DATA = {
  "Centre Essonne": {
    "BONDOUFLE": [
      "Rue de Villeroy - All. Edmond Delfours - Rue des Trois Parts",
      "Rue de Villeroy - Rue des Clos - Rue des Trois Parts",
      "Rue de Villeroy - Rue Gutemberg",
      "Rue Gutemberg - Rue Georges Pompidou"
    ],
    "EVRY": [
      "N7 Bd. Jean Jaures -Centre Hospitalier SUD Francilien",
      "RN7 (Bd Jean Jaures) - Rue de l'Internationale - Rue Pierre Fontaine - SNECMA",
      "Bd du Marechal De Lattre de Tassigny - Rue du Bel Air - Ch. De la Grange Feu Louis",
      "Bd. Du Marechal De Lattre de Tassigny - Bd des Coquibus - Rue Maurice Ravel",
      "Bd. Du Marechal De Lattre de Tassigny - Rond Point du Parc aux Lievres",
      "Bd. Des Coquibus -Gare RER Bras de Fer",
      "Bd des Coquibus - RN7 (Entrees/Sorties)",
      "Bd des Coquibus - Imp. Alexis Trinquet",
      "Bd des Coquibus - Bd Louise Michel",
      "Bd des Coquibus - Rue Charles Fourier",
      "Bd des Coquibus - Bd de France - Rue des Gaston Cremieux",
      "Bd des Coquibus - Rue Henri Rochefort",
      "Bd des Coquibus - Rue des Mazieres",
      "Bd des Coquibus - Cours Blaise Pascal - Cours Mgr Romero",
      "P.P. Bd Francois Mitterand - Gare",
      "Bd Francois Mitterrand - Rue Ambroise Croizat - Rue Pere Andre Jarlan",
      "Bd. Louise Michel - Place des Federes",
      "Bd Louise Michel - Rue de l'Internationale - Rue Jean Malezieux",
      "Bd de l'Yerres - Rue de l'Essonne",
      "Bd de L'Yerres - Rue Boissy d'Anglas - Voie TU",
      "Bd de l'Yerres - Acces Les Estudines - Voie TU",
      "Bd de l'Yerres - Av. du Lac",
      "Bd des Champs Elysees - Rue de l'Abbe Gregoire - Parking Indigo",
      "Bd des Champs Elysees - Bd de l'Europe",
      "Bd des Champs Elysees - Rue des Galants Courts",
      "Bd des Champs Elysees - Bd de L'Ecoute S'Il Pleut",
      "Bd des Champs Elysees - Rue Jules Valles",
      "Bd des Champs Elysees - Clinique de l'Essone - Voie TU",
      "Bd des Champs Elysees - Rue Paul Claudel - Rue du Bois Guillaume",
      "Bd des Champs Elysees - RN7 (Entrees/Sorties)",
      "Bd des Champs Elysees - Rue Gutenberg",
      "Av. de la Liberte - Rue des Grands Champs",
      "Av. de la Liberte - Av. de Ratisbonne",
      "Bd. Decauville - All. L.B. de Bourbon",
      "Bd Decauville - Rue Montespan - Rue d'Antin",
      "Bd. Decauville - Av. Nowy Targ",
      "Bd. Decauville - Bd Aguado - Rue Emmanuel Pastre",
      "P.P. Rue Rossini",
      "Bd du Marechal Leclerc - Av. Nowy Targ - Voie TU",
      "Bd de l'Europe - Rue des Mazieres - Rue du Facteur Cheval",
      "Bd de l'Europe - Desserte Aristide Canlorbe - Mc Donald",
      "Bd de l'Europe - Av. de l'Orme a Martin",
      "Bd de l'Europe - Bd de L'Ecoute S'Il Pleut",
      "Rue Montespan - Rue Descartes",
      "Rue des Galants Courts - Rue du Facteur Cheval - Voie TU",
      "P.P. 205 Rue Pierre et Marie Curie",
      "Rue Jules Valles - Pl. Salvador Allende - Voie TU",
      "Bd de L'Ecoute S'Il Pleut - Rue Jean Anouilh",
      "Rue du Bois Sauvage - Av. de l'Aunette - Voie TU",
      "Rue du Bois Guillaume - Rte de Mennecy",
      "Rue Promethee - Av. Nowy Targ (Voie TU)",
      "Bd de France - Rue Promethee",
      "Bd de France - Av. de la Prefecture",
      "D91 - D93 - Bd de France-Georges Pompidou - Bretelle N7 Entree/Sortie",
      "P.P. Av. du Marechal Juin",
      "Av. du General Patton - Av. de Mousseau - Rue du 8 Mai 1945",
      "Av. du General Patton - Av. Fragonard",
      "Av. de Mousseau - Av. Fragonard - Rue Claude Debussy",
      "Imp. Alexis Trinquet - Voie TU",
      "Imp. Jean Malezieux - All. De la Butte Rouge (VoieTU)",
      "Rue Henri Rochefort - All. De la Butte Rouge (Voie TU)",
      "Rue de l'Essonne - Rue de l'Ecole - Voie TU",
      "All. Boissy d'Anglas - Voie TU - Bd. De l'Yerres",
      "Av. Simone Veil - Voie TU + P.P. TU",
      "Cours Monseigneur Romero - Voie TU"
    ],
    "COURCOURONNES": [
      "Av. Paul Delouvrier -Bd des Champs Elysees - Bd Francois Mitterand",
      "Av. Paul Delouvrier - Sortie A6",
      "Bd des Champs Elysees - Rue Georges Brassens - Rue Leopold Sedar Senghor",
      "Bd des Champs Elysees - Rue Jaques Tati",
      "Bd des Champs Elysees - Rue Jean Renoir",
      "Rue Jean Renoir - Voie TU",
      "Rue du Marquis de Raies - Rue des Freres Lumiere - Rue Jacques Tati",
      "Rue du Marquis de Raies - Rue Georges Brassens",
      "Rue du Marquis de Raies - Place du Printemps",
      "Av. de l'Orme a Martin - Rue du Marquis de Raies - Rue du Plessis Briard",
      "Rue du Pont Amar - Rue de la Boissee - Voie TU",
      "Av. de l'Orme a Martin - Rue du Pont Amar",
      "Av. de l'Orme a Martin - Rue des Osiers - Rue Jean Mermoz",
      "Av. Pierre Beregovoy - Av. G.Clemenceau",
      "Av. Pierre Beregovoy - Rue de la Cerisaie",
      "Av. Pierre Beregovoy - Rue du Cygnes",
      "Av. Pierre Beregovoy - Rue Ambroise Pare - Parc du Lac",
      "Rue Alcide de Gasperi - Av. de la Petite Montagne - Rue de la Mare Neuve - Voie TU",
      "Rue Noel Marteau - Rue Joseph Letien",
      "COURCOURONNES TRAM T12"
    ],
    "GRIGNY": [
      "P.P. Av. Emile Aillaud - Rue du Ravin",
      "Av. Emile Aillaud - Rue Dedale - Rue du Ravin",
      "Av. Emile Aillaud - Rue Condorcet - Voie Athena",
      "Av. Emile Aillaud - Rue Diderot - Rue des Batisseurs",
      "P.P. Av. de la premiere armee Rhin Danube - Rue Avicenne - Mosquee de Grigny",
      "Av. de la premiere armee Rhin Danube - Ch. de Corbeil",
      "Av. de la premiere armee Rhin Danube - Gare Grigny Centre RER",
      "Rue de Louise Michel Rte de Corbeil Sortie parking Square Rodin",
      "Rte de Corbeil Rue des Jardins de la Ferme - Rle du Cure",
      "Rte de Corbeil - Rue Pierre Brossolette - Ch. du Plessis",
      "Route de Corbeil Ecole Maternelle les Tilleuls - Mairie de Grigny",
      "Ch. du Moulin Rue Guy Mocquet - Rue de Schio",
      "Ch. du Plessis Promenade du Canal - Rue du 17 Octobre 1961",
      "RN7 Rue Ferdinand De Lesseps",
      "RN7 - Sortie Truffaut",
      "RN7 - Ch. du Port - Rue du Port",
      "P.P. 8/10 Rue Gustave Eiffel (Sortie entreprises FAYAT et SAML)"
    ],
    "LISSES": [
      "LISSES 8 Mai 1945 - Peupliers",
      "LISSES 8 Mai 1945 - Adam de la Halle",
      "LISSES 8 Mai 1945 - Christine de Pisan",
      "LISSES 8 Mai 1945 - Parcs",
      "LISSES Parcs - Malines",
      "LISSES Paris - Bois de la Place",
      "LISSES Paris - Corbeil",
      "LISSES Gal de Gaulle - Aulnes",
      "LISSES Parcs - M.Roche",
      "LISSES D26 - Clos au pois",
      "LISSES Parcs - Leonard de Vinci",
      "LISSES Villabe - entree A6",
      "LISSES Corbeil - Longaines"
    ],
    "RIS-ORANGIS": [
      "RIS-ORANGIS RN7 - Glaise",
      "RIS-ORANGIS RN7 - Reckitt",
      "RIS-ORANGIS RN7 - Clos",
      "RIS-ORANGIS RN7 - E.Bonte",
      "RIS-ORANGIS RN7 - J.jaures",
      "RIS-ORANGIS RN7 - Fontaine",
      "RIS-ORANGIS P.Brossolette - Fusilles",
      "RIS-ORANGIS P.Brossolette - Grigny",
      "RIS-ORANGIS P.Brossolette - Sand",
      "RIS-ORANGIS P.Brossolette - Papin",
      "RIS-ORANGIS P.Brossolette - Cime",
      "RIS-ORANGIS P.Brossolette - Mouchot",
      "RIS-ORANGIS P.Brossolette - Monthlery",
      "RIS-ORANGIS Aunette - College J.Lurcat",
      "RIS-ORANGIS Resistance - Plessis Briard",
      "RIS-ORANGIS P.P Cime",
      "RIS-ORANGIS P.P Maternelle Fauvettes",
      "RIS-ORANGIS Grigny - J.Jaures",
      "RIS-ORANGIS Grigny - Chateau d'Eau",
      "RIS-ORANGIS Grigny - Clos Langlet",
      "RIS-ORANGIS PP - RN7",
      "RIS-ORANGIS Chateau D'Eau - Moulin a Vent",
      "RIS-ORANGIS Chateau D'Eau - Orangis Picasso",
      "RIS-ORANGIS Resistance - LE PLAN2",
      "RIS-ORANGIS RN7 - P.P Total Acces"
    ],
    "VILLABE": [
      "VILLABE Sortie BUS - Route de Lisses",
      "VILLABE Vielle cote - Bas cornus",
      "VILLABE Vielle cote - 8Mai 1945",
      "VILLABE Sortie Ecole J.Jaures",
      "VILLABE Ormoy - Bas des Brettes"
    ]
  },
  "Seine Essonne": {
    "COMBS-LA-VILLE": [
      "Av de Quincy - Av Victor Hugo - All. des Peupliers",
      "P.P. Av de Quincy - Ecole Beausoleil",
      "Av. du Gal. Leclerc - Av de la Republique - Rue Sommeville - Rue Therese Delapierre",
      "Rue Jean Moulin - Rue de Lieusaint",
      "Rue Pablo Picasso - Rue Jean Moulin - Rue Jean Francois Millet",
      "P.P. Rue de l'Abreuvoir - All. des Grives",
      "Rue du Chene - Rue du Marche - Av. de la Marrache",
      "P.P. Lycee Jacques Prevert - Av. Jean Jaures",
      "P.P. Ecole Oree du Bois - Rue du Bois l'Eveque"
    ],
    "CORBEIL-ESSONNES": [
      "RN7 (Bd John Kennedy) - RD191 (Av. des Roissy Hauts)",
      "RN7 (Bd. John Kennedy) - Ch. des Ronfleurs",
      "RN7 (Bd John Kennedy) - Ch. De la Cavignon",
      "P.P. 161 Bd. John Kennedy RN7",
      "RN7 (Bd John Kennedy) - Rue Balzac - Rue du Chene",
      "RN7 (Bd John Kennedy) - Ecole Pauline Kergomard",
      "RN7 (Bd John Kennedy) - Ch. du Cgb (Chemin de Fer de Grande Banlieue)",
      "RN7 (Bd John Kennedy) - Rue St Lazare",
      "RN7 (Bd John Kennedy - Bd de Fontainebleau) - Bd Henri Dunant",
      "RN7 (Rue de Paris - Bd de Fontainebleau) - Rue de la Dauphine - Rue Louis Joyeux",
      "RN7 (Rue de Paris) - Rue de Gournay - Rue d'Angouleme",
      "RN7 (Rue de Paris) - Pl. Leon Casse - Rue du Pere Legris",
      "RN7 (Rue de Paris) - Rue Marchand",
      "QUICK: Pl. de Sindelfingen - Rue de Paris - Rue Feray - Rue de Robinson - Bd Georges Michel - Bd du Mal. De Lattre de Tassigny",
      "QUICK: Pl. de Sindelfingen - Rue de Paris - Rue de Robinson - Bd du Mal. De Lattre de Tassigny - (Armoire a cote de COR-SLT-03)",
      "RN7 (Bd Jean Jaures) -Rue de l'Alouette",
      "RN7 (Bd Jean Jaures) - Route des Lisses",
      "P.P. RN7 (Bd Jean Jaures) - Av Serge Dassault - Sortie Parking Lycee Robert Doisneau",
      "RN7 (Bd Jean Jaures) - Pl. des Anciens Combattants d'Afn et d'Indochine",
      "RN7 (Bd. Jean Jaures) Entree/Sortie RN104",
      "Av. du 8 Mai 1945 - Rue des Vergers - Rue la Fontaine",
      "Av. Gal. De Gaulle - Av. Serge Dassault - Voie TZEN4",
      "Av. Serge Dassault - Rue Henri Matisse - Voie TZEN4",
      "Av. Serge Dassault - Rue de la Bruyere - Voie TZEN4",
      "Av. Serge Dassault - Rue Charles Robin - Voie TZEN4",
      "Rue Emile Zola - Av. Serge Dassault - Voie TZEN4 - Gare routiere",
      "Rue Emile Zola - Rue La Fayette",
      "Rue Emile Zola - Av. Leon Blum",
      "Av. Paul Maintenant - Rte de Lisses",
      "Av. Paul Maintenant - Rue Jacques Anquetil - Rue des Pepinieres",
      "Av. Paul Maintenant - McDonald's",
      "Av. du Gal. De Gaulle - Rue Pablo Picasso",
      "P.P. Av. du Gal. De Gaulle - College Leopold Sedar Senghor",
      "P.P. Mosquee: Av. du Gal. De Gaulle - Rue Auguste Renoir",
      "Rue du Mal. De Lattre de Tassigny - Parking \"Marche Frais\"",
      "Av. Carnot - Rue Feray",
      "Av. Carnot - Rue du Dr Vignes",
      "Rue du Gal. Leclerc - Rue Felicien Rops",
      "Rue du Gal. Leclerc - Rue de Seine",
      "Rue de Seine - Av. Darblay - Rue du Gal. Lucotte",
      "Bd. Louis Lecouillard - Rue Fernand Laguide - Rue de la Nacelle",
      "Rue de la nacelle - Rue Bernardin de Saint-Pierre",
      "P.P. Rue de la Papeterie - Rue Paul et Virginie",
      "Bd Combes Marne - Rue d'Angouleme",
      "Place d'Essonnes - Bd Combes Marnes - Bd Jules Valles",
      "Bd Henri Dunant - Av. du Pr. Allende- Caserne Sapeurs Pompiers",
      "Bd. Henri Dunant - Rue Marcel Paul",
      "Boulevard Henri Dunant - Rue Gilles de Corbeil",
      "Bd. Henri Dunant - CDAU SDIS91 (Centre de secours) - Ch. Des Mozards",
      "Bd Henri Dunant - Av. Rene Pierre - Rue Belvedere",
      "Bd Henri Dunant - Rue de la Dauphine",
      "Bd Henri Dunant Rue Lamartine",
      "Bd Henri Dunant - Rue de Gournay",
      "Rue Chevalier - Av. Carnot Bd Henri Dunant Rue Saint Spire",
      "P.P. St Spire - Rue des Fosses",
      "Quai Jacques Bourgoin - Rue de la Triperie - Gare Routiere",
      "Pl. du Comte Haymon - Quai Mauzaisse - Quai Jacques Bourgoin - Rue St Spire - Rue Notre Dame",
      "Quai de l'Apport Paris - Rue Decauville",
      "Quai de l'Apport Paris - Rue Fernand Raynaud (Sortie TATA)",
      "Quai Maurice Riquiez - Quai des Platanes - Rue de Montgarde",
      "Quai Maurice Riquiez - Rue de la Tuilerie - Rue de la Guinguette",
      "Rue Waldeck Rousseau - Rue Audiffred Bastide - Rue du 14 Juillet",
      "Rue Waldeck Rousseau - Square des Peupliers",
      "P.P. Ecole Theodore Steeg - Rue Paul Bert"
    ],
    "ETIOLLES": [
      "RD448 (2 Av. du General De Gaulle) - Residence les deux marquises",
      "RD448 (Av. de la Font au Soulier) - Av. Charles De Gaulle - Ch. Du Port aux Paveurs",
      "RD448 (Av. de la Font au Soulier) - RD331 (Rue Collardeau)",
      "RD331 (Rue des Bordes) - Rue des Patenottes - Ch. De Villouvette"
    ],
    "LE COUDRAY-MONTCEAUX": [
      "RN7 (Av. Charles de Gaulle) - Rue de Bouligneau - All. du Coudray",
      "Av. Charles de Gaulle - Rue du Martelet - All. du Coudray - Gare routiere",
      "Av. Charles de Gaulle - All. des Ecureuils - Rue de la Clef des Champs",
      "Av. Charles de Gaulle - Rue Gabrielle d'Estrees - Rue des Verts Domaines",
      "RN7 (Av. Charles de Gaulle) - Rue de Milly - P.P. Rond Point du Grand Pacha de l'Himalaya",
      "RN7 (Bd. John Kennedy) - Sortie X-FAB France",
      "RD191 (Av. des Roissy Hauts) - Entree X-FAB France"
    ],
    "SAINT-GERMAIN-LES-CORBEIL": [
      "N 01 De Gaulle Val Fleury",
      "N 02 Rte de Lieusaint mairie Darblay",
      "N 03 Rochefort tuilerie",
      "N 04 Leclerc Etiolles Villouvette"
    ],
    "MORSANG SUR SEINE": [
      "MORSANG SUR SEINE"
    ]
  },
  "Senart": {
    "LIEUSAINT": [
      "D402 OLYMPE DE GOUGE",
      "AV.PIERRE POINT SORTIE GARE ROUTIERE",
      "Rue du COLOMBIER RUE DE PARIS",
      "Ave PIERRE POINT Bd OLYMPE DE GOUGE",
      "D402 COTE DE L ENTRE DEUX",
      "D402 FERME DE VARATRE",
      "AV PIERRE POINT - PARIS",
      "D402 MOULIN A VENT",
      "TRAIT D UNION COTE DE LA COMMUNAUTE",
      "TRAIT D UNION HOTEL CLARION SUITES",
      "TRAIT D UNION POINT DE VUE NORD",
      "TRAIT D UNION ALLEE DE LAVANT SCENE",
      "TRAIT D UNION POINT DE VUE SUD",
      "POINT DE VUE ALLEE DE L ECHANGE",
      "POINT DE VUE CARRE DES ARTS",
      "POINT DE VUE ALLEE DE LA TOLERANCE",
      "ALLEE DE LA TOLERANCE COTE DE L ENTRE DEUX",
      "PP BD EUROPE",
      "TRAIT UNION -COTE DE LA BIENVENUE"
    ],
    "MOISSY-CRAMAYEL": [
      "ALTERNAT 1 RUE DENIS PAPIN ZAC DARVIGNY"
    ],
    "SAINT-PIERRE-DU-PERRAY": [
      "Rue de la MAIRIE Ecole CHANTEFABLES",
      "Rue Victor HUGO Allee de VILLERAY",
      "GENDARMERIE CHEMIN DE BRIE",
      "RTE DE MONTGARDE ALLEE BOURGOIN",
      "Bd CHRISTIAN JULLIEN RUE DES CYGNES",
      "Bd CHRISTIAN JULLIEN RUE MOZART",
      "AV. TOUR MAURY RUE DU GRAND MAURY",
      "AV. TOUR MAURY RUE DES PRES HAUTS",
      "AV. TOUR MAURY RUE DE LA MARE A TISSIER",
      "AV.TOUR MAURY RTE DE VILLEPECLE",
      "D33 PASSAGE DE MAUPERTHUIS"
    ],
    "SAVIGNY-LE-TEMPLE": [
      "RD50 - CUEILLETTE",
      "AVENUE 8 MAI 1945 - RUE DE LA GRANGE",
      "AVENUE DE GAULLE - RUE DES PROVINCES",
      "AVENUE DE GAULLE - AVENUE DE L EUROPE",
      "AVENUE DE GAULLE - RUE DE ROUGEAU",
      "RUE DE ROUGEAU - ALLEE DE PERSPECTIVE"
    ],
    "SOISY-SUR-SEINE": [
      "SOISY-SUR-SEINE RD448 / Liberation / Du Rendez-Vous / Rue des Meillottes",
      "SOISY-SUR-SEINE Bd de la republique / Bd Briand / Bd Vandeul",
      "SOISY-SUR-SEINE E.Warin / F.Bourgeois / Vandeul / L'Oiseau",
      "SOISY-SUR-SEINE De Gaulle / Marronnier / Residence des 2 Marquises",
      "SOISY-SUR-SEINE De Gaulle / Seine / Berthelot"
    ],
    "TIGERY": [
      "Rte de Lieusaint Rue Roland Delplanque",
      "P.P. BOULEVARD DES PAYS-BAS",
      "Rte de Lieusaint - Rue de la Bergerie - Rue du Cmdt. Maurice Lissac"
    ],
    "NANDY": [
      "NANDY"
    ],
    "REAU": [
      "REAU"
    ],
    "SAINTRY-SUR-SEINE": [
      "SAINTRY-SUR-SEINE"
    ],
    "VERT-SAINT-DENIS": [
      "VERT-SAINT-DENIS"
    ]
  }
};